// <auto-generated />
using System;
using BikeAnalyzerAPI.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeAnalyzerAPI.Migrations
{
    [DbContext(typeof(BikeDbContext))]
    [Migration("20220930160111_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BikeAnalyzerAPI.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("HeadTubeAngle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RimWidth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SeatTubeEffectiveAngle")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TireWidth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TravelBackWheel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TravelFrontWheel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Weigth")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("YearOfProduction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bikes");
                });
#pragma warning restore 612, 618
        }
    }
}
